Proyecto para prueba de Doxygen: cripto_funciones.h File Reference
cripto_funciones.h File Reference
#include <iostream>
#include <fstream>
#include <string>
Functions
void Usage (int argc, char *argv[])
Muestra el modo de uso correcto del programa En caso de que el uso no sea el correcto, muestra el mensaje y finaliza la ejecución del programa.
void ComprobarParametros (char *argv[])
Comprueba que los parámetros introducidos son los necesarios para el correcto proceso de encriptado, en caso contrario imprime en pantalla el mensaje de error correspondiente indicando que parámetro es incorrecto.
bool IsInteger (std::string str)
La siguiente función IsInteger comprueba si el parámetro k que se introduce por línea de comandos es realmente un número entero, tal y como se precisa.
std::string EncriptadoXor (std::string contenido, std::string clave)
A continuación, se presenta una función que encripta un fichero con el método de XOR.
std::string EncriptadoCesar (std::string contenido, const int k)
A continuación, se presenta una función que encripta un fichero con el método de césar.
std::string DesencriptadoCesar (std::string contenido, const int k)
A continuación, se presenta una función que desencripta un fichero previamente encriptado con el método de césar.
Variables
const std::string kHelpText
Function Documentation
ComprobarParametros()
void ComprobarParametros (char * argv[])
Comprueba que los parámetros introducidos son los necesarios para el correcto proceso de encriptado, en caso contrario imprime en pantalla el mensaje de error correspondiente indicando que parámetro es incorrecto.
Definition at line 40 of file cripto_funciones.cc.
References IsInteger().
Referenced by main().
{
   if (argv[3][0] != '1' && argv[3][0] != '2'){
     std::cout << "Error en el método de encriptado" << std::endl;
     exit(EXIT_FAILURE);
   }
   if (argv[3][0] == '2'){
     std::string k{argv[4][0]};
     if(IsInteger(k)){
     }
     else{
       std::cout << "Error en el método de encriptado" << std::endl;
       exit(EXIT_FAILURE);
     }
   }
   if (argv[5][0] != '+' && argv[5][0] != '-'){
     std::cout << "Error en la operación" << std::endl;
     exit(EXIT_FAILURE);
   }
 }
DesencriptadoCesar()
std::string DesencriptadoCesar (std::string contenido, const int k)
A continuación, se presenta una función que desencripta un fichero previamente encriptado con el método de césar.
A la función se le pasa el contenido del fichero y la constate k.
Definition at line 112 of file cripto_funciones.cc.
Referenced by main().
{
   std::string contenido_desencriptado;
   for (int i = 0; i < contenido.length(); ++i){
     char caracter_evaluar = contenido[i];
     int caracter = caracter_evaluar;
     caracter -= k;
     char caracter_nuevo{caracter};
     contenido_desencriptado += caracter_nuevo;
   }
   return contenido_desencriptado;
 }
EncriptadoCesar()
std::string EncriptadoCesar (std::string contenido, const int k)
A continuación, se presenta una función que encripta un fichero con el método de césar.
A la función se le pasa el contenido del fichero y la constate k.
Definition at line 96 of file cripto_funciones.cc.
Referenced by main().
{
   std::string contenido_encriptado;
   for (int i = 0; i < contenido.length(); ++i){
     char caracter_evaluar = contenido[i];
     int caracter = caracter_evaluar;
     caracter += k;
     char caracter_nuevo{caracter};
     contenido_encriptado += caracter_nuevo;
   }
   return contenido_encriptado;
 }
EncriptadoXor()
std::string EncriptadoXor (std::string contenido, std::string clave)
A continuación, se presenta una función que encripta un fichero con el método de XOR.
A la función se le pasa el contenido del fichero y la clave o contraseña correspondiente.
Definition at line 79 of file cripto_funciones.cc.
Referenced by main().
{
   std::string contenido_encriptado{""};
   std::string clave_encriptada{""};
   for (auto i : clave){
     clave_encriptada += (clave[i]^128);
     std::cout << clave_encriptada;
   }
   for (int i : contenido){
     contenido_encriptado += (contenido[i]^clave_encriptada[i%clave_encriptada.length()]);
   }
   return contenido_encriptado;
 }
IsInteger()
bool IsInteger (std::string str)
La siguiente función IsInteger comprueba si el parámetro k que se introduce por línea de comandos es realmente un número entero, tal y como se precisa.
Definition at line 66 of file cripto_funciones.cc.
Referenced by ComprobarParametros().
{
   for(auto c: str){
     if(c < 48 || c > 57)
       return false;
   }
   return true;
 }
Usage()
void Usage (int argc, char * argv[])
Muestra el modo de uso correcto del programa En caso de que el uso no sea el correcto, muestra el mensaje y finaliza la ejecución del programa.
Parameters
[in] argc Number of command line parameters
[in] argv Vector containing (char*) the parameters
Definition at line 15 of file cripto_funciones.cc.
References kHelpText.
Referenced by main().
{
   if (argc == 1 && argc != 6) {
     std::cout << argv[0] << ": faltan parámetros" << std::endl;
     std::cout << "Pruebe " << argv[0] << " --help para más información" << std::endl;
     exit(EXIT_SUCCESS);
   }
   if (argc == 2){
     std::string parameter{argv[1]};
     if (parameter == "--help") {
       std::cout << kHelpText << std::endl;
       exit(EXIT_SUCCESS);
     }
   }
   if (argc != 6){
     std::cout << argv[0] << ": faltan parámetros" << std::endl;
     std::cout << "Pruebe " << argv[0] << " --help para más información" << std::endl;
     exit(EXIT_SUCCESS);
   }
 }
Variable Documentation
kHelpText
const std::string kHelpText
Initial value:
= R"(fichero_entrada: Fichero a codificar
fichero_salida:  Fichero codificado
método:          Indica el método de encriptado
                   1: Cifrado xor
                   2: Cifrado de César
password:        Palabra secreta en el caso de método 1, Valor de K en el método 2
operación:       Operación a realizar en el fichero
                   +: encriptar el fichero
                   -: desencriptar el fichero)"
Definition at line 5 of file cripto_funciones.h.
Referenced by Usage().